image: node:10.6

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    untracked: true
  script:
    - npm install
  tags:
    - docker
  artifacts:
    paths:
      - reports/

deploy_production:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  tags:
    - docker
  environment:
    name: production
    url: https://vientoenelrio.com
  script:
    - npm install
    - ./deploy_to_production.sh
#  when: manual
  only:
    - master
