image: node:10.6

stages:
  - build
  - test
  - deploy

yarn:
  stage: build
  cache:
    untracked: true
  script:
    - yarn install
  tags: 
    - docker
  artifacts:
    paths:
      - reports/

run_tests:
  stage: test
  cache:
    untracked: true
    policy: pull
  script:
    - yarn install
    - yarn test
  tags:
    - docker
  artifacts:
    paths:
      - reports/

deploy_development:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  tags:
    - docker
  environment:
    name: development
    url: http://qr.amalgama.co
  script:
    - yarn install
    - ./deploy_to_development.sh
  dependencies:
    - run_tests
  only:
    - master